name: build-test-deploy

on: 
  push:
    branches:
      master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: default
        target: wasm32-unknown-unknown
        components: rustfmt, clippy

  fmt:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

  install-deps:
    runs-on: ubuntu-latest

    steps:
    - name: Install build deps
      run: sudo apt-get install libasound2-dev xorg-dev libgl1-mesa-glx

    - name: Install wasm-bindgen
      uses: jetli/wasm-bindgen-action@v0.1.0
      with:
        version: 'latest'
    
    - name: Install binaryen
      run: |
        set -e
        curl -L https://github.com/WebAssembly/binaryen/releases/download/1.39.1/binaryen-1.39.1-x86_64-linux.tar.gz | tar xzf -
        echo "`pwd`/binaryen-1.39.1" > $GITHUB_PATH
  
  test:
    needs: [setup, install-deps]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Run clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings

    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
    
  build:
    needs: [setup, install-deps]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Build and run wasm-bindgen
      run: |
        ./build_wasm.sh main --release

  deploy:
    needs: [setup, install-deps, build]
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: web # The folder the action should deploy.
        CLEAN: true
        CLEAN_EXCLUDE: '["CNAME"]'